name: Viraj Prabhu
description: "Life, Computer Science and Everything"
meta_description: "Viraj Prabhu on Life, Computer Science and Everything"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
paginate_path: "/blog/page:num/"
baseurl: /
domain_name: 'http://virajprabhu.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Viraj Prabhu'

gems:
  - jekyll-sitemap

social-icons:
 - title: GitHub
   url: https://github.com/virajprabhu
   class: github
 - title: LinkedIn
   url: https://in.linkedin.com/pub/viraj-prabhu/35/a94/a2
   class: linkedin
 - title: Twitter
   url: https://twitter.com/virajp93
   class: twitter